# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
 - php: 5.6
   env: WP_TRAVISCI=travis:phpunit
   
# optionally specify a list of environments, for example to test different RDBMS
# env:
  #- DB=mysql
  
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

after_success:
    - bash <(curl -s https://codecov.io/bash)

# configure notifications (email, IRC, campfire etc)
#notifications:
 # irc: "irc.freenode.org#yourfavouriteroomfortravis"
