# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to a recent 5.6.x version
   - 5.6
  # aliased to a recent 7.x version
   - 7.0

# optionally specify a list of environments, for example to test different RDBMS
# env:
  #- DB=mysql
  
before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

after_success:
    - bash <(curl -s https://codecov.io/bash)

# configure notifications (email, IRC, campfire etc)
#notifications:
 # irc: "irc.freenode.org#yourfavouriteroomfortravis"
    
  deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  on:
    branch: main
